architectury {
    fabric()
}

base {
    archivesName = "${mod_id}+fabric"
}

sourceSets {
    main {
        java {
            srcDir project(':common').sourceSets.main.java
        }
        resources {
            srcDir project(':common').sourceSets.main.resources
        }
    }
}

loom {
    runs {
        client {
            client()
            programArgs "--username", "Dev"
        }
        server {
            server()
            programArgs "--nogui"
        }
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    include 'com.moandjiezana.toml:toml4j:0.7.2'
    implementation 'com.moandjiezana.toml:toml4j:0.7.2'
    modImplementation "dev.isxander:yet-another-config-lib:${project.yacl_version_fabric}"
    modCompileOnly "curse.maven:backpacked-352835:7866686"
    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")
    modCompileOnly("maven.modrinth:inventorio:${project.inventorio_fabric_version}")
    modImplementation("io.wispforest:accessories-fabric:${project.accessories_version}")
    modImplementation "maven.modrinth:jade:${project.jade_fabric_version}"
    modImplementation "dev.emi:trinkets:${project.trinkets_version}"
    modCompileOnly("dev.ryanhcode.sable:sable-common-${project.minecraft_version}:${project.sable_version}")

}

tasks.named('processResources') {
    def replaceProperties = [
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            mod_license            : mod_license,
            minecraft_version_range: minecraft_version_range,
            fabric_loader_version  : fabric_loader_version,
            fabric_api_version     : fabric_api_version,
            yacl_version_fabric    : yacl_version_fabric
    ]
    inputs.properties replaceProperties

    filesMatching("fabric.mod.json") {
        expand replaceProperties
    }
    filesMatching("*.mixins.json") {
        expand replaceProperties
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
tasks.named('sourcesJar') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}