architectury {
    common('neoforge', 'fabric')
}

sourceSets {
    main {
        resources {
            srcDir 'src/main/resources'
        }
    }
}

dependencies {
    compileOnly "org.spongepowered:mixin:0.8.5"
    implementation 'com.moandjiezana.toml:toml4j:0.7.2'
    annotationProcessor "org.spongepowered:mixin:0.8.5"
    modCompileOnly "curse.maven:backpacked-352835:${project.backpacked_version}"
    modCompileOnly("io.wispforest:accessories-common:${project.accessories_version}")
    modCompileOnly("io.wispforest:accessories-neoforge:${project.accessories_version}")
    modImplementation "maven.modrinth:jade:${project.jade_version}"
    modCompileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    modCompileOnly "maven.modrinth:trinkets:${project.trinkets_version}"
    modApi("dev.ryanhcode.sable:sable-common-${project.minecraft_version}:${project.sable_version}")
    modCompileOnly "maven.modrinth:inventorio:${project.inventorio_fabric_version}"
    modCompileOnly "dev.isxander:yet-another-config-lib:${project.yacl_version_fabric}"
}