architectury {
    neoForge()
}

base {
    archivesName = "${mod_id}+neo"
}

configurations {
    includeEmbedded
    include.extendsFrom(includeEmbedded)
}

sourceSets {
    main {
        java {
            srcDir project(':common').sourceSets.main.java
        }
        resources {
            srcDir project(':common').sourceSets.main.resources
        }
    }
}

loom {
    runs {
        client {
            client()
            programArgs "--username", "Dev"
        }
        server {
            server()
            programArgs "--nogui"
        }
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:${project.neo_version}"

    modCompileOnly "curse.maven:backpacked-352835:7866688"
    implementation "dev.isxander:yet-another-config-lib:${project.yacl_version_neoforge}"
    modCompileOnly "maven.modrinth:inventorio:${project.inventorio_neo_version}"
    modImplementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    modImplementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    modCompileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    modRuntimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    modImplementation("com.tterrag.registrate:Registrate:${registrate_version}")
    modImplementation("maven.modrinth:vercte-satchels:${project.satchels_version}")
    modImplementation "dev.simulated_team.simulated:simulated-neoforge-${project.minecraft_version}:${project.simulated_version}"
    modImplementation "maven.modrinth:create-aeronautics:${project.simulated_version}+mc${project.minecraft_version}"
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    modCompileOnly("io.wispforest:accessories-neoforge:${project.accessories_version}")
    modImplementation "maven.modrinth:jade:${project.jade_version}"
    modCompileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    modRuntimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"
    modApi("dev.ryanhcode.sable:sable-common-${project.minecraft_version}:${project.sable_version}")
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version_range: minecraft_version_range,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            yacl_version_neoforge  : yacl_version_neoforge
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
tasks.ideaSyncTask.dependsOn generateModMetadata
tasks.named('processResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
tasks.named('sourcesJar') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}